apiVersion: v1
kind: Service
metadata:
  name: gruappbackendservice
spec:
  selector:
    app: gruappbackendlabel
  type: LoadBalancer
  ports:
    - name: gruappbackendport
      port: 80
      targetPort: 8000
  externalIPs:
    - 192.168.49.2