apiVersion: v1
kind: Service
metadata:
  name: gruappdatabaseservice
  labels: 
    name: gruappdatabasestatefulset
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: gruappmongolabel